# Simple workflow for deploying a React app to GitHub Pages
name: Deploy static content to Pages

on:
  push:
    branches: ['main'] # Troque "react" pela sua branch de deploy, como você mencionou
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npx eslint . --ext .js,.jsx

      - name: Build the React app
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build' # Diretório da build

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
